# Generated by Django 3.1.3 on 2021-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
